name: automock
description: An automatic mock server to speed up your initial development.
version: 1.4.0
homepage: https://github.com/mauriciotogneri/automock

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.0
  mockserver: ^1.4.0

dev_dependencies:
  build_runner: ^1.11.5
  http: ^0.13.0
  json_serializable: ^4.0.2
  test: ^1.16.5