name: automock
description: An automatic mock server to speed up your initial development.
version: 1.4.0
homepage: https://github.com/mauriciotogneri/automock

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  mockserver: ^1.4.0

dev_dependencies:
  build_runner: ^1.10.0
  http: ^0.12.2
  json_serializable: ^3.4.1
  test: ^1.15.3