name: automock
description: An automatic mock server to speed up your initial development.
version: 1.2.1
homepage: https://github.com/mauriciotogneri/automock

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  mockserver: ^1.2.1

dev_dependencies:
  json_serializable: ^3.3.0
  build_runner: ^1.10.0
  http: ^0.12.1
  test: ^1.14.5